version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            cmake --version
